"""Business categories to search for in each metro area."""

CATEGORIES = [
    "restaurants",
    "plumbers",
    "electricians",
    "dentists",
    "auto repair",
    "hair salon",
    "barber shop",
    "real estate agent",
    "lawyers",
    "accountants",
    "chiropractor",
    "pet grooming",
    "landscaping",
    "cleaning service",
    "roofing",
    "HVAC",
    "painters",
    "photographers",
    "tutors",
    "yoga studio",
    "florist",
    "bakery",
    "car wash",
    "daycare",
    "gym",
    "insurance agent",
    "moving company",
    "pest control",
    "printing service",
    "tattoo shop",
    "tree services",
]
