"""Top 50 US metropolitan areas for lead scraping."""

METROS = [
    {"name": "New York", "search_term": "New York NY", "state": "NY"},
    {"name": "Los Angeles", "search_term": "Los Angeles CA", "state": "CA"},
    {"name": "Chicago", "search_term": "Chicago IL", "state": "IL"},
    {"name": "Dallas", "search_term": "Dallas TX", "state": "TX"},
    {"name": "Houston", "search_term": "Houston TX", "state": "TX"},
    {"name": "Washington DC", "search_term": "Washington DC", "state": "DC"},
    {"name": "Philadelphia", "search_term": "Philadelphia PA", "state": "PA"},
    {"name": "Miami", "search_term": "Miami FL", "state": "FL"},
    {"name": "Atlanta", "search_term": "Atlanta GA", "state": "GA"},
    {"name": "Boston", "search_term": "Boston MA", "state": "MA"},
    {"name": "Phoenix", "search_term": "Phoenix AZ", "state": "AZ"},
    {"name": "San Francisco", "search_term": "San Francisco CA", "state": "CA"},
    {"name": "Riverside", "search_term": "Riverside CA", "state": "CA"},
    {"name": "Detroit", "search_term": "Detroit MI", "state": "MI"},
    {"name": "Seattle", "search_term": "Seattle WA", "state": "WA"},
    {"name": "Minneapolis", "search_term": "Minneapolis MN", "state": "MN"},
    {"name": "San Diego", "search_term": "San Diego CA", "state": "CA"},
    {"name": "Tampa", "search_term": "Tampa FL", "state": "FL"},
    {"name": "Denver", "search_term": "Denver CO", "state": "CO"},
    {"name": "St. Louis", "search_term": "St Louis MO", "state": "MO"},
    {"name": "Baltimore", "search_term": "Baltimore MD", "state": "MD"},
    {"name": "Orlando", "search_term": "Orlando FL", "state": "FL"},
    {"name": "Charlotte", "search_term": "Charlotte NC", "state": "NC"},
    {"name": "San Antonio", "search_term": "San Antonio TX", "state": "TX"},
    {"name": "Portland", "search_term": "Portland OR", "state": "OR"},
    {"name": "Sacramento", "search_term": "Sacramento CA", "state": "CA"},
    {"name": "Pittsburgh", "search_term": "Pittsburgh PA", "state": "PA"},
    {"name": "Las Vegas", "search_term": "Las Vegas NV", "state": "NV"},
    {"name": "Austin", "search_term": "Austin TX", "state": "TX"},
    {"name": "Cincinnati", "search_term": "Cincinnati OH", "state": "OH"},
    {"name": "Kansas City", "search_term": "Kansas City MO", "state": "MO"},
    {"name": "Columbus", "search_term": "Columbus OH", "state": "OH"},
    {"name": "Indianapolis", "search_term": "Indianapolis IN", "state": "IN"},
    {"name": "Cleveland", "search_term": "Cleveland OH", "state": "OH"},
    {"name": "San Jose", "search_term": "San Jose CA", "state": "CA"},
    {"name": "Nashville", "search_term": "Nashville TN", "state": "TN"},
    {"name": "Virginia Beach", "search_term": "Virginia Beach VA", "state": "VA"},
    {"name": "Providence", "search_term": "Providence RI", "state": "RI"},
    {"name": "Milwaukee", "search_term": "Milwaukee WI", "state": "WI"},
    {"name": "Jacksonville", "search_term": "Jacksonville FL", "state": "FL"},
    {"name": "Memphis", "search_term": "Memphis TN", "state": "TN"},
    {"name": "Oklahoma City", "search_term": "Oklahoma City OK", "state": "OK"},
    {"name": "Raleigh", "search_term": "Raleigh NC", "state": "NC"},
    {"name": "Richmond", "search_term": "Richmond VA", "state": "VA"},
    {"name": "Louisville", "search_term": "Louisville KY", "state": "KY"},
    {"name": "New Orleans", "search_term": "New Orleans LA", "state": "LA"},
    {"name": "Salt Lake City", "search_term": "Salt Lake City UT", "state": "UT"},
    {"name": "Hartford", "search_term": "Hartford CT", "state": "CT"},
    {"name": "Birmingham", "search_term": "Birmingham AL", "state": "AL"},
    {"name": "Buffalo", "search_term": "Buffalo NY", "state": "NY"},
]
